name = "BlackJack"
uuid = "cb8df6fc-8dfc-4458-9a11-511f2bdd34b4"
authors = ["Pedro Gomes <pedrogbranquinho@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
PlayingCards = "ecfe714a-bcc2-4d11-ad00-25525ff8f984"
Shuffle = "bf21e494-c40e-4daa-abfb-de5ec0aad010"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
